import React from 'react';
import { Helmet } from 'react-helmet';
import {
  BrainCircuit,
  Flower2,
  Sprout,
  Target,
  ScanSearch,
  CheckCircle2,
  Image as ImageIcon,
  ShieldCheck,
} from 'lucide-react';

import DashboardLayout from '../components/DashboardLayout.jsx';
import {
  Card,
  CardHeader,
  CardTitle,
  CardContent,
} from '../components/ui/card';
import { Badge } from '../components/ui/badge';
import { Progress } from '../components/ui/progress';


// =========================================================
// TEMPORARY AI RESULT
// Generated by:
// apple_detector.py
// pollination_decision.py
// ai_pipeline.py
//
// Later this data will come from FastAPI.
// =========================================================

const aiResult = {
  crop: 'apple',

  image: 'IMG_0044.jpg',

  imageWidth: 807,

  imageHeight: 605,

  total_detections: 33,

  apple_flower_count: 7,

  bud_count: 26,

  flower_confidence_threshold: 0.5,

  potential_pollination_targets: 6,

  status: 'AI_ANALYSIS_COMPLETE',

  targets: [
    {
      target_id: 1,
      target_type: 'apple_flower',
      confidence: 0.779,
      bounding_box: {
        x1: 593.95,
        y1: 289.96,
        x2: 616.08,
        y2: 311.67,
      },
      decision: 'potential_pollination_target',
    },

    {
      target_id: 2,
      target_type: 'apple_flower',
      confidence: 0.7789,
      bounding_box: {
        x1: 541.9,
        y1: 110.47,
        x2: 567.45,
        y2: 134.48,
      },
      decision: 'potential_pollination_target',
    },

    {
      target_id: 3,
      target_type: 'apple_flower',
      confidence: 0.7619,
      bounding_box: {
        x1: 550.39,
        y1: 451.04,
        x2: 606.92,
        y2: 498.5,
      },
      decision: 'potential_pollination_target',
    },

    {
      target_id: 4,
      target_type: 'apple_flower',
      confidence: 0.7413,
      bounding_box: {
        x1: 617.11,
        y1: 378.45,
        x2: 671.75,
        y2: 434.51,
      },
      decision: 'potential_pollination_target',
    },

    {
      target_id: 5,
      target_type: 'apple_flower',
      confidence: 0.7259,
      bounding_box: {
        x1: 252.31,
        y1: 239.43,
        x2: 276.03,
        y2: 263.45,
      },
      decision: 'potential_pollination_target',
    },

    {
      target_id: 6,
      target_type: 'apple_flower',
      confidence: 0.6853,
      bounding_box: {
        x1: 292.81,
        y1: 271.87,
        x2: 309.78,
        y2: 288.96,
      },
      decision: 'potential_pollination_target',
    },
  ],
};


// =========================================================
// STAT CARD
// =========================================================

const StatCard = ({
  title,
  value,
  description,
  icon: Icon,
  iconClass,
}) => {
  return (
    <Card className="hover:shadow-lg transition-all duration-200">

      <CardContent className="p-5">

        <div className="flex items-start justify-between">

          <div>

            <p className="text-sm text-muted-foreground">
              {title}
            </p>

            <p className="text-3xl font-bold mt-2">
              {value}
            </p>

            <p className="text-xs text-muted-foreground mt-1">
              {description}
            </p>

          </div>

          <div
            className={`w-11 h-11 rounded-xl flex items-center justify-center ${iconClass}`}
          >
            <Icon className="w-5 h-5" />
          </div>

        </div>

      </CardContent>

    </Card>
  );
};


// =========================================================
// DETECTION BOX
// =========================================================

const DetectionBox = ({
  target,
  imageWidth,
  imageHeight,
}) => {

  const {
    x1,
    y1,
    x2,
    y2,
  } = target.bounding_box;

  // Convert original pixel coordinates
  // into percentages so the box remains
  // correctly positioned when the image scales.

  const left = (x1 / imageWidth) * 100;

  const top = (y1 / imageHeight) * 100;

  const width =
    ((x2 - x1) / imageWidth) * 100;

  const height =
    ((y2 - y1) / imageHeight) * 100;

  const confidence =
    Math.round(target.confidence * 1000) / 10;

  return (
    <div
      className="absolute border-2 border-green-500 pointer-events-none"
      style={{
        left: `${left}%`,
        top: `${top}%`,
        width: `${width}%`,
        height: `${height}%`,
      }}
    >

      {/* Target label */}

      <div
        className="absolute -top-7 left-0 whitespace-nowrap
                   bg-green-600 text-white text-[10px]
                   sm:text-xs font-semibold px-2 py-1
                   rounded-md shadow-md"
      >
        T{String(target.target_id).padStart(2, '0')}
        {' '}
        {confidence}%
      </div>

    </div>
  );
};


// =========================================================
// AI ANALYSIS PAGE
// =========================================================

const AIAnalysis = () => {

  const flowerPercentage =
    aiResult.total_detections > 0
      ? (
          aiResult.apple_flower_count /
          aiResult.total_detections
        ) * 100
      : 0;

  const budPercentage =
    aiResult.total_detections > 0
      ? (
          aiResult.bud_count /
          aiResult.total_detections
        ) * 100
      : 0;

  const targetPercentage =
    aiResult.apple_flower_count > 0
      ? (
          aiResult.potential_pollination_targets /
          aiResult.apple_flower_count
        ) * 100
      : 0;


  return (
    <DashboardLayout>

      <Helmet>

        <title>
          Apple AI Analysis - MelissaNektarion
        </title>

      </Helmet>


      <div className="space-y-6">


        {/* ================================================= */}
        {/* PAGE HEADER */}
        {/* ================================================= */}

        <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">

          <div className="flex items-center gap-3">

            <div className="w-11 h-11 rounded-xl bg-primary/10 flex items-center justify-center">

              <BrainCircuit className="w-6 h-6 text-primary" />

            </div>

            <div>

              <h1 className="text-3xl font-bold leading-tight">
                AI Analysis
              </h1>

              <p className="text-muted-foreground mt-1">
                Apple flower and bud detection
              </p>

            </div>

          </div>


          <Badge
            variant="outline"
            className="w-fit flex items-center gap-2 px-3 py-2"
          >

            <CheckCircle2 className="w-4 h-4 text-green-600" />

            AI Analysis Complete

          </Badge>

        </div>


        {/* ================================================= */}
        {/* CROP INFORMATION */}
        {/* ================================================= */}

        <Card>

          <CardContent className="p-5">

            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">

              <div className="flex items-center gap-3">

                <div className="w-12 h-12 rounded-xl bg-green-500/10 flex items-center justify-center">

                  <Sprout className="w-6 h-6 text-green-600" />

                </div>

                <div>

                  <p className="text-sm text-muted-foreground">
                    Analyzed Crop
                  </p>

                  <h2 className="text-xl font-bold capitalize">
                    {aiResult.crop}
                  </h2>

                </div>

              </div>


              <div className="text-left sm:text-right">

                <p className="text-sm text-muted-foreground">
                  Image
                </p>

                <p className="font-medium">
                  {aiResult.image}
                </p>

              </div>

            </div>

          </CardContent>

        </Card>


        {/* ================================================= */}
        {/* STAT CARDS */}
        {/* ================================================= */}

        <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-6">

          <StatCard
            title="Total Detections"
            value={aiResult.total_detections}
            description="Objects detected by AI"
            icon={ScanSearch}
            iconClass="bg-blue-500/10 text-blue-600"
          />

          <StatCard
            title="Apple Flowers"
            value={aiResult.apple_flower_count}
            description="Flowers detected"
            icon={Flower2}
            iconClass="bg-pink-500/10 text-pink-600"
          />

          <StatCard
            title="Buds"
            value={aiResult.bud_count}
            description="Buds detected"
            icon={Sprout}
            iconClass="bg-amber-500/10 text-amber-600"
          />

          <StatCard
            title="Pollination Targets"
            value={aiResult.potential_pollination_targets}
            description="Potential targets"
            icon={Target}
            iconClass="bg-green-500/10 text-green-600"
          />

        </div>


        {/* ================================================= */}
        {/* IMAGE + TARGET SUMMARY */}
        {/* ================================================= */}

        <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">


          {/* =============================================== */}
          {/* AI IMAGE */}
          {/* =============================================== */}

          <Card className="xl:col-span-2">

            <CardHeader>

              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">

                <CardTitle className="flex items-center gap-2">

                  <ImageIcon className="w-5 h-5 text-primary" />

                  AI Detection Image

                </CardTitle>


                <div className="flex items-center gap-2">

                  <Badge
                    variant="outline"
                    className="text-green-600 border-green-600/30"
                  >
                    6 Targets
                  </Badge>

                  <Badge variant="secondary">
                    Apple
                  </Badge>

                </div>

              </div>

            </CardHeader>


            <CardContent>

              {/* Image wrapper */}

              <div className="w-full rounded-xl overflow-hidden border bg-muted">

                <div
                  className="relative w-full"
                  style={{
                    aspectRatio: `${aiResult.imageWidth} / ${aiResult.imageHeight}`,
                  }}
                >

                  {/* Actual image */}

                  <img
                    src="/ai-images/IMG_0044.jpg"
                    alt="Apple orchard AI detection"
                    className="absolute inset-0 w-full h-full object-contain"
                  />


                  {/* AI target boxes */}

                  {aiResult.targets.map((target) => (

                    <DetectionBox
                      key={target.target_id}
                      target={target}
                      imageWidth={aiResult.imageWidth}
                      imageHeight={aiResult.imageHeight}
                    />

                  ))}

                </div>

              </div>


              {/* Legend */}

              <div className="flex flex-wrap items-center gap-4 mt-4 text-sm">

                <div className="flex items-center gap-2">

                  <span className="w-4 h-4 border-2 border-green-500 rounded-sm" />

                  <span className="text-muted-foreground">
                    Potential pollination target
                  </span>

                </div>


                <div className="text-muted-foreground">
                  Green boxes show flowers accepted by the prototype decision rule.
                </div>

              </div>

            </CardContent>

          </Card>


          {/* =============================================== */}
          {/* TARGET SUMMARY */}
          {/* =============================================== */}

          <Card>

            <CardHeader>

              <CardTitle className="flex items-center gap-2">

                <Target className="w-5 h-5 text-green-600" />

                Target Summary

              </CardTitle>

            </CardHeader>


            <CardContent className="space-y-4">

              <div className="rounded-xl bg-green-500/10 p-5">

                <p className="text-sm text-muted-foreground">
                  Potential Targets
                </p>

                <p className="text-4xl font-bold text-green-600 mt-1">
                  {aiResult.potential_pollination_targets}
                </p>

              </div>


              <div>

                <div className="flex justify-between mb-2">

                  <span className="text-sm">
                    Accepted flowers
                  </span>

                  <span className="text-sm font-medium">
                    {Math.round(targetPercentage)}%
                  </span>

                </div>

                <Progress value={targetPercentage} />

              </div>


              <div className="border-t pt-4">

                <div className="flex items-center gap-2 mb-2">

                  <ShieldCheck className="w-4 h-4 text-green-600" />

                  <span className="font-medium text-sm">
                    Decision rule
                  </span>

                </div>

                <p className="text-sm text-muted-foreground">

                  Apple flowers with confidence ≥ 0.50
                  are considered potential targets.
                  Buds are ignored.

                </p>

              </div>


              <Badge
                variant="outline"
                className="w-full justify-center py-2 text-green-600 border-green-600/30"
              >
                No hardware action triggered
              </Badge>

            </CardContent>

          </Card>

        </div>


        {/* ================================================= */}
        {/* DETECTION SUMMARY */}
        {/* ================================================= */}

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">


          <Card>

            <CardHeader>

              <CardTitle className="flex items-center gap-2">

                <ScanSearch className="w-5 h-5 text-primary" />

                Detection Summary

              </CardTitle>

            </CardHeader>


            <CardContent className="space-y-6">


              <div>

                <div className="flex justify-between mb-2">

                  <span className="text-sm font-medium">
                    Apple Flowers
                  </span>

                  <span className="text-sm text-muted-foreground">
                    {aiResult.apple_flower_count} / {aiResult.total_detections}
                  </span>

                </div>

                <Progress value={flowerPercentage} />

              </div>


              <div>

                <div className="flex justify-between mb-2">

                  <span className="text-sm font-medium">
                    Buds
                  </span>

                  <span className="text-sm text-muted-foreground">
                    {aiResult.bud_count} / {aiResult.total_detections}
                  </span>

                </div>

                <Progress value={budPercentage} />

              </div>


              <div className="pt-2 border-t">

                <div className="flex justify-between">

                  <span className="text-sm text-muted-foreground">
                    Confidence threshold
                  </span>

                  <Badge variant="secondary">
                    {aiResult.flower_confidence_threshold}
                  </Badge>

                </div>

              </div>

            </CardContent>

          </Card>


          {/* ================================================= */}
          {/* POLLINATION DECISION */}
          {/* ================================================= */}

          <Card>

            <CardHeader>

              <CardTitle className="flex items-center gap-2">

                <Target className="w-5 h-5 text-green-600" />

                Pollination Decision

              </CardTitle>

            </CardHeader>


            <CardContent className="space-y-5">

              <div className="flex items-center justify-between p-4 rounded-xl bg-green-500/10">

                <div>

                  <p className="text-sm text-muted-foreground">
                    Potential targets
                  </p>

                  <p className="text-3xl font-bold text-green-600">
                    {aiResult.potential_pollination_targets}
                  </p>

                </div>

                <Target className="w-9 h-9 text-green-600" />

              </div>


              <div className="flex items-center gap-3 p-4 rounded-xl border">

                <CheckCircle2 className="w-5 h-5 text-green-600 shrink-0" />

                <div>

                  <p className="font-medium">
                    Decision completed
                  </p>

                  <p className="text-sm text-muted-foreground mt-1">
                    Six flower detections passed the
                    prototype confidence rule.

                  </p>

                </div>

              </div>

            </CardContent>

          </Card>

        </div>


        {/* ================================================= */}
        {/* TARGET LIST */}
        {/* ================================================= */}

        <Card>

          <CardHeader>

            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">

              <CardTitle className="flex items-center gap-2">

                <Target className="w-5 h-5 text-green-600" />

                Potential Pollination Targets

              </CardTitle>


              <Badge variant="secondary">

                {aiResult.potential_pollination_targets} targets

              </Badge>

            </div>

          </CardHeader>


          <CardContent>

            <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">

              {aiResult.targets.map((target) => {

                const confidencePercentage =
                  Math.round(
                    target.confidence * 1000
                  ) / 10;

                return (

                  <div
                    key={target.target_id}
                    className="rounded-xl border p-4 hover:shadow-md transition-all duration-200"
                  >

                    <div className="flex items-start justify-between gap-3">

                      <div className="flex items-center gap-3">

                        <div className="w-10 h-10 rounded-lg bg-green-500/10 flex items-center justify-center">

                          <Flower2 className="w-5 h-5 text-green-600" />

                        </div>

                        <div>

                          <p className="font-semibold">
                            Target {String(
                              target.target_id
                            ).padStart(2, '0')}
                          </p>

                          <p className="text-xs text-muted-foreground">
                            Apple Flower
                          </p>

                        </div>

                      </div>


                      <Badge className="bg-green-600">

                        {confidencePercentage}%

                      </Badge>

                    </div>


                    <div className="mt-4">

                      <div className="flex justify-between text-xs mb-2">

                        <span className="text-muted-foreground">
                          Confidence
                        </span>

                        <span className="font-medium">
                          {confidencePercentage}%
                        </span>

                      </div>

                      <Progress value={confidencePercentage} />

                    </div>


                    <div className="mt-4 pt-3 border-t">

                      <p className="text-xs text-muted-foreground mb-1">
                        Bounding Box
                      </p>

                      <p className="text-xs font-mono break-all">
                        x1: {target.bounding_box.x1}
                        {' | '}
                        y1: {target.bounding_box.y1}
                        {' | '}
                        x2: {target.bounding_box.x2}
                        {' | '}
                        y2: {target.bounding_box.y2}
                      </p>

                    </div>


                    <div className="mt-3">

                      <Badge
                        variant="outline"
                        className="text-green-600 border-green-600/30"
                      >
                        Potential Target
                      </Badge>

                    </div>

                  </div>

                );

              })}

            </div>

          </CardContent>

        </Card>


        {/* ================================================= */}
        {/* PROTOTYPE NOTICE */}
        {/* ================================================= */}

        <div className="rounded-xl border bg-muted/30 p-4">

          <p className="text-sm text-muted-foreground">

            <strong className="text-foreground">
              Prototype AI decision:
            </strong>{' '}

            detected apple flowers meeting the confidence
            threshold are classified as potential pollination
            targets. The current prototype does not directly
            activate the pollination hardware.

          </p>

        </div>


      </div>

    </DashboardLayout>
  );
};


export default AIAnalysis;